import 'package:my_shop/core/l10n/l10n.dart';

extension AppLocalizationsKey on AppLocalizations {
  String byKey(String key) => switch (key) {
    'storyNew' => storyNew,
    'storyDecor' => storyDecor,
    'storyAccessories' => storyAccessories,
    'storyCare' => storyCare,
    'productLamp' => productLamp,
    'productCandle' => productCandle,
    'productLinen' => productLinen,
    'productBowl' => productBowl,
    'productVase' => productVase,
    'productChair' => productChair,
    'productPerfume' => productPerfume,
    'productDecor' => productDecor,
    'categoryClothing' => categoryClothing,
    'categoryShoes' => categoryShoes,
    'categoryAccessories' => categoryAccessories,
    'categoryElectronics' => categoryElectronics,
    'categoryBooks' => categoryBooks,
    'categoryHome' => categoryHome,
    'catalogLinenShirt' => catalogLinenShirt,
    'catalogWoolCoat' => catalogWoolCoat,
    'catalogSilkDress' => catalogSilkDress,
    'catalogCottonTrousers' => catalogCottonTrousers,
    'catalogLeatherSneakers' => catalogLeatherSneakers,
    'catalogClassicLoafers' => catalogClassicLoafers,
    'catalogSuedeBoots' => catalogSuedeBoots,
    'catalogMinimalSandals' => catalogMinimalSandals,
    'catalogLeatherBag' => catalogLeatherBag,
    'catalogGoldEarrings' => catalogGoldEarrings,
    'catalogSilkScarf' => catalogSilkScarf,
    'catalogClassicWatch' => catalogClassicWatch,
    'catalogWirelessHeadphones' => catalogWirelessHeadphones,
    'catalogSmartSpeaker' => catalogSmartSpeaker,
    'catalogCompactCamera' => catalogCompactCamera,
    'catalogPortableCharger' => catalogPortableCharger,
    'catalogDesignBook' => catalogDesignBook,
    'catalogArchitectureAlbum' => catalogArchitectureAlbum,
    'catalogArtHistory' => catalogArtHistory,
    'catalogModernInteriors' => catalogModernInteriors,
    'catalogCeramicVase' => catalogCeramicVase,
    'catalogAmberCandles' => catalogAmberCandles,
    'catalogGeometryPoster' => catalogGeometryPoster,
    'catalogJuteBasket' => catalogJuteBasket,
    _ => key,
  };
}
