import 'package:my_shop/core/constants/constants.dart';
import 'package:my_shop/core/l10n/l10n.dart';

extension AppLocalizationsKey on AppLocalizations {
  String byKey(String key) => switch (key) {
    LocalizationKeys.storyNew => storyNew,
    LocalizationKeys.storyDecor => storyDecor,
    LocalizationKeys.storyAccessories => storyAccessories,
    LocalizationKeys.storyCare => storyCare,
    LocalizationKeys.productLamp => productLamp,
    LocalizationKeys.productCandle => productCandle,
    LocalizationKeys.productLinen => productLinen,
    LocalizationKeys.productBowl => productBowl,
    LocalizationKeys.productVase => productVase,
    LocalizationKeys.productChair => productChair,
    LocalizationKeys.productPerfume => productPerfume,
    LocalizationKeys.productDecor => productDecor,
    LocalizationKeys.categoryClothing => categoryClothing,
    LocalizationKeys.categoryShoes => categoryShoes,
    LocalizationKeys.categoryAccessories => categoryAccessories,
    LocalizationKeys.categoryElectronics => categoryElectronics,
    LocalizationKeys.categoryBooks => categoryBooks,
    LocalizationKeys.categoryHome => categoryHome,
    LocalizationKeys.catalogLinenShirt => catalogLinenShirt,
    LocalizationKeys.catalogWoolCoat => catalogWoolCoat,
    LocalizationKeys.catalogSilkDress => catalogSilkDress,
    LocalizationKeys.catalogCottonTrousers => catalogCottonTrousers,
    LocalizationKeys.catalogLeatherSneakers => catalogLeatherSneakers,
    LocalizationKeys.catalogClassicLoafers => catalogClassicLoafers,
    LocalizationKeys.catalogSuedeBoots => catalogSuedeBoots,
    LocalizationKeys.catalogMinimalSandals => catalogMinimalSandals,
    LocalizationKeys.catalogLeatherBag => catalogLeatherBag,
    LocalizationKeys.catalogGoldEarrings => catalogGoldEarrings,
    LocalizationKeys.catalogSilkScarf => catalogSilkScarf,
    LocalizationKeys.catalogClassicWatch => catalogClassicWatch,
    LocalizationKeys.catalogWirelessHeadphones => catalogWirelessHeadphones,
    LocalizationKeys.catalogSmartSpeaker => catalogSmartSpeaker,
    LocalizationKeys.catalogCompactCamera => catalogCompactCamera,
    LocalizationKeys.catalogPortableCharger => catalogPortableCharger,
    LocalizationKeys.catalogDesignBook => catalogDesignBook,
    LocalizationKeys.catalogArchitectureAlbum => catalogArchitectureAlbum,
    LocalizationKeys.catalogArtHistory => catalogArtHistory,
    LocalizationKeys.catalogModernInteriors => catalogModernInteriors,
    LocalizationKeys.catalogCeramicVase => catalogCeramicVase,
    LocalizationKeys.catalogAmberCandles => catalogAmberCandles,
    LocalizationKeys.catalogGeometryPoster => catalogGeometryPoster,
    LocalizationKeys.catalogJuteBasket => catalogJuteBasket,
    _ => key,
  };
}
